# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: conjur-demo
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  fetch-secret-from-conjur:
    runs-on: ubuntu-latest
    steps:
      - name: debug-step 
        run: echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN" | base64
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: infamousjoeg/conjur-action@v2.0.3
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: cybrlab
          authn_id: ${{ secrets.CONJUR_AUTHN_ID }}
          secrets: github/apps/safe/secret1|SECRET1;github/apps/safe/secret2|SECRET2;github/apps/safe/secret3|SECRET3
          certificate: ${{ secrets.CONJUR_PUBLIC_KEY }}
      - name : Echo Secret1
        run: echo $SECRET1 | sed 's/./& /g'       
      - name : Echo Secret2
        run: echo $SECRET2 | sed 's/./& /g' 
      - name : Echo Secret3
        run: echo $SECRET3 | sed 's/./& /g' 

